export const TODOADDED = "TODOADDED";
export const TODOTOGGLED = "TODOTOGGLED";
export const COLORSELECTED = "COLORSELECTED";
export const TODODELETED = 'TODODELETED';
export const ALLCOMPLETED = "ALLCOMPLETED";
export const COMPLETEDCLEARED = "COMPLETEDCLEARED";
export const STATUSFILTERCHANGED = "STATUSFILTERCHANGED";
export const COLORFILTERCHANGED = "COLORFILTERCHANGED";

